# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NeighborhoodMap
                                 A QGIS plugin
 NeighborhoodMap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-10
        copyright            : (C) 2022 by mahdinazari.info
        email                : mahdinazari75@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NeighborhoodMap class from file NeighborhoodMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .neighborhood_map import NeighborhoodMap
    return NeighborhoodMap(iface)
